[workspace]
changelog_update = false
git_release_enable = false
semver_check = false

[[package]]
name = "evm-testnet"
release = false

[[package]]
name = "test-utils"
release = false

[[package]]
name = "autonomi-nodejs"
release = false

[[package]]
name = "ant-node-nodejs"
release = false
