name: Label Check

on:
  pull_request:
      branches: ["*"]
      types: [labeled, unlabeled, opened, synchronize, auto_merge_enabled]

jobs:
  check-do-not-merge-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has DoNotMerge label
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo -e "This PR has the following Labels:\n$LABELS"
          if [[ $LABELS == *"DoNotMerge"* ]]; then
            echo "::warning::This PR is labeled as DoNotMerge! Please remove this label before merging."
            echo "This PR has the DoNotMerge label but the check will still pass."
          else
            echo "✓ PR does not have DoNotMerge label"
          fi
